version: '3.7'
services:
  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: 9mREsvXDs9Gk89Ef
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    ports:
      - 5432:5432
    volumes:
      - ./var:/lib/postgresql/data