version: '3.8'
services:
  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: 9mREsvXDs9Gk89Ef
    ports:
      - 5432:5432
    volumes:
      - /data:/var/lib/postgresql/data